### PR TITLE
added disable-search-engine-choice flag

### PR DESCRIPTION
**Pull request by LtCMDstone**

### CODE REVIEW

**Comment by cal4** [comment]
Is this a draft? Please mark it as such if so

**Comment by LtCMDstone** [comment]
Not really a draft, just a mini PR to disable the search engine select with chrome 127

**Review by klept0 — APPROVED** [review]

**Comment by LtCMDstone** [comment]
@klept0 @cal4 
The flag is gone again? :smile:

**Comment by klept0** [comment]
Cal was working on things so I would need to defer to him on that one but Im sure we can easily re-add it

**Pull request merged**
