### PR TITLE
Use a blacklist for falsely detected activities

### PR DESCRIPTION
**Pull request by Kyrela**
This simple PR adds a list that contains detected activities that can't be completed (or where it isn't applicable), just like "Safeguard your family's info".

### CODE REVIEW

**Comment by cal4** [comment]
Good idea, but this is somewhat implemented already. See https://github.com/klept0/MS-Rewards-Farmer/blob/c269afb35c077ca06c057694e701dcdf93359965/src/activities.py#L254-L260. The main difference here is that the ignorable activities are configurable (with ignore by default).

At the time, I thought there might be some value in allowing the ignores to be configurable but now that I think about it more there doesn't seem to be any value to this. What do you think?

**Comment by Kyrela** [comment]
Sorry I didn't see it. Looks like It's only configurable for notifications. Not very useless imo but hey, you never know. The only problems I have with the current implementation are:
- Hard-coded: The config rely on `ignore-safeguard-info` for this specific activity. I think something like
  ```
  incomplete-activity:
    enabled: True
    blacklist:
      - "Safeguard your family's info"
  ```
  would be more dynamic - doesn't require some code changes to ignore another activity not listed by the program
- Duplicated: The Current implementation ignores the activity in all cases, even if the ignore-safeguard-info is set to False. Seems perfectly logical, but requires two different lists: one that is static, and the other that is configurable. I thnik that it would be simpler if the activities to ignore were just based of the notification configuration - that'll make it a generic configuration and not specifically related to notifications. Don't know if this can be done without problems. But, if we keep the two logics separated, my PR still stands, I'll just have to add notification configuration for this.
  
Anyway, I'll try to come up with something else shortly, as a proposition. Probably something that's configuration based. Closing this, I'll open another PR, thanks for the feedback!

**Comment by cal4** [comment]
Yeah I agree, a list of titles to ignore is more flexible. I'd recommend `incomplete-activity.ignore` as opposed to `incomplete-activity.blacklist` since it reads a bit better IMO.

This would deprecate `ignore-safeguard-info`, which we should remove of course.

**Comment by cal4** [comment]
Made this change here: https://github.com/klept0/MS-Rewards-Farmer/commit/2bf51d38a57af2f802e1f7ac7977fef3726c9f4a

**Comment by Kyrela** [comment]
> Anyway, I'll try to come up with something else shortly, as a proposition. Probably something that's configuration based. Closing this, I'll open another PR, thanks for the feedback!

Done, see #248

**Pull request closed without merging**
