### PR TITLE
Docker implementation

### PR DESCRIPTION
**Pull request by belgio99**
Moved the (still WIP) Docker Implementation PR from @charlesbel's repo.

Old discussion can be found [here](https://github.com/charlesbel/Microsoft-Rewards-Farmer/pull/431).

Currently it supports two environmental variables:

- `RUN_ONCE`: if set to `true`, runs the script once and then quits
- `CRON_SCHEDULE`: you can supply a valid cron schedule, or by default it will just run daily at 4 AM.

Builds can be auto-triggered (GitHub Actions) by setting a tag to the commits.

TODO:

- [ ] Pass command line options to the script
- [ ]  ??? (Suggestions are very much welcomed!)

### CODE REVIEW

**Comment by sealldeveloper** [comment]
Looking good, I'll give it a test in the background and give some feedback (if i have any)

**Comment by sealldeveloper** [comment]
Hitting a crash with current master branch of kelpt0 with the `Dockerfile` built.

```
Traceback (most recent call last):
  File "/app/main.py", line 42, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 200, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/login.py", line 45, in login
    self.utils.goHome()
  File "/app/src/utils.py", line 129, in goHome
    self.webdriver.get(BASE_URL)
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=126.0.6478.114)
```

**Comment by SgtSobieski** [comment]
Can a dockerfile be constructed in a way that it rebuilds the latest repository if the latest repository is downloaded?

**Comment by cal4** [comment]
Yeah, typically you'd have a CI pipeline that triggers a build

**Comment by belgio99** [comment]
Exactly. Typically you should avoid pulling the latest repo in a Dockerfile.
This is done in order to make the builds reproducible, and to allow other versions of the project to be built.
The Dockerfile should build the version chosen using `git checkout`.

**Comment by ttraxxrepo** [comment]
Hey all - any updates on this? Looks like checks have passed?

**Comment by klept0** [comment]
If this needs to come out of draft then @belgio99 can flip it to ready and we can check then push

**Comment by belgio99** [comment]
Images are ready to go on Docker Hub on `supercar99/ms-rewards`. In the last commit, I changed the semantic versioning to align it with the rest of the project.

One thing when merging: make sure that the Docker Hub secrets (username & token) are configured correctly before merging, or the action won't be able to push to Docker Hub. Now they are configured with my secrets, but I assume that merging the PR will auto switch to @klept0's secrets (not sure about this).

It all LGTM about this Docker implementation. Feel free to test the images, feedback is always appreciated!

**Comment by cal4** [comment]
Thanks @belgio99, I'm debating whether to include the ci stuff simply because I'd like prefer for people to build via the Dockerfile until we test this out a bit more, but good to know in regards to secrets

**Comment by ttraxxrepo** [comment]
@belgio99 is there a docker-compose.yml that can be referenced to spin the supercar99/ms-rewards up?

**Comment by fuchaohan** [comment]
> Images are ready to go on Docker Hub on `supercar99/ms-rewards`. In the last commit, I changed the semantic versioning to align it with the rest of the project.映像已准备好在 `supercar99/ms-rewards` 上的 Docker Hub 上运行。在最后一次提交中，我更改了语义版本控制，使其与项目的其余部分保持一致。
> 
> One thing when merging: make sure that the Docker Hub secrets (username & token) are configured correctly before merging, or the action won't be able to push to Docker Hub. Now they are configured with my secrets, but I assume that merging the PR will auto switch to @klept0's secrets (not sure about this).合并时的一件事：确保在合并前正确配置了 Docker Hub 秘密（用户名和令牌），否则作将无法推送到 Docker Hub。现在它们已经配置了我的秘密，但我假设合并 PR 会自动切换到 的秘密（不确定这一点）。
> 
> It all LGTM about this Docker implementation. Feel free to test the images, feedback is always appreciated!这一切都是关于这个 Docker 实现的 LGTM。欢迎随时测试图片，我们始终不胜感激！

Can you update the docker image? Thank you. Every time I build  it fails

**Comment by cal4** [comment]
@fuchaohan What error are you getting?

**Pull request merged**
