### PR TITLE
Add command line option to do either mobile or desktop search only

### PR DESCRIPTION
**Pull request by jeondungpoop**
Added command line option for user to do searches only with desktop browser or mobile browser. Default behavior without setting the command line option is running both. I removed the random pauses before and after sleep because I think it is redundant when we already have delays set in the Searches class but please do let me know if it vital for avoiding suspicions. I also moved the step for reading articles into mobile searches to split up the tasks a bit. I'll mark this as a draft for now since I'm still testing and want to touch up logging a bit but please do leave suggestions and feedback :smiley: 

Edit: Now updated to be more in line with the existing code in the `develop` branch. Please disregard some of the statements above.

### CODE REVIEW

**Comment by cal4** [comment]
Looks good to me, I'd just request we merge this to develop which is upstream of master. Lets us test out a bit and less complicated to merge master with changes back to develop.

#137 is close to stable, hoping to release to master soon.

**Comment by jeondungpoop** [comment]
> Looks good to me, I'd just request we merge this to develop which is upstream of master. Lets us test out a bit and avoids having to merge back to develop which'll most likely cause conflicts.
> 
> #137 is close to stable, hoping to release to master soon (we can totally wait on these changes).

Thank you for taking a look and letting me know there is a develop branch. I totally did not notice that, that's my bad. Anyways, rebased and updated the code to match with what we have in the develop branch. I'm going to test this more tomorrow so leaving it as a draft for now.

**Comment by cal4** [comment]
> > Looks good to me, I'd just request we merge this to develop which is upstream of master. Lets us test out a bit and avoids having to merge back to develop which'll most likely cause conflicts.
> > #137 is close to stable, hoping to release to master soon (we can totally wait on these changes).
> 
> Thank you for taking a look and letting me know there is a develop branch. I totally did not notice that, that's my bad. Anyways, rebased and updated the code to match with what we have in the develop branch. I'm going to test this more tomorrow so leaving it as a draft for now.

All good, dev branch's very new. I need to update the README.

**Comment by cal4** [comment]
Looks good

**Comment by jeondungpoop** [comment]
Hands-on testing with selecting either desktop search or mobile search or both went smoothly. I ran into an issue with the searches not scoring points and basically went through all 8 retires.  This happens rather randomly. Sometimes it's on the 8th search term group and then basically all search terms after that will fail and not get points. Some other times it's the last search term group. I'll poke around more using a new account to see what the cause.

**Comment by cal4** [comment]
Gotcha, that's happening in develop as well. From what I can tell, rewards count on the server side isn't always immediately reflected, but delayed.

Either way should be good to merge.

**Pull request merged**
