### PR TITLE
WebDriver Quit Bug Fix

### PR DESCRIPTION
**Pull request by jungx098**
This patch resolves https://github.com/klept0/MS-Rewards-Farmer/issues/126.

### CODE REVIEW

**Comment by jdeath** [comment]
I still get a crash in docker (I know, unique use case). If I use quit alone it works fine. if I use close or close/quit it crashes. I did not try quit/close . I am running in docker, so do not care about orphan processes, but understand others do care.

**Comment by klept0** [comment]
This was put in and removed - https://github.com/klept0/MS-Rewards-Farmer/issues/112

**Comment by jungx098** [comment]
@jdeath Sorry to hear that this PR does not work on your system. Can you figure out the root cause? My issue was because the mobile driver tried to access the session data that the desktop driver occupied. See https://github.com/klept0/MS-Rewards-Farmer/issues/126.

@klept0 I verified this PR resolved https://github.com/klept0/MS-Rewards-Farmer/issues/112 on my MacOS with https://github.com/klept0/MS-Rewards-Farmer/pull/127/commits/7ccba44497e8957357d7a96c93ef5619e11b1278  that https://github.com/klept0/MS-Rewards-Farmer/issues/112 missed. Can you please test this PR on your system?

**Comment by cal4** [comment]
Getting rid of the redundant closeBrowser calls is a good idea (did the same in #120), but what fixed #126 for me was [this](https://github.com/cal4/MS-Rewards-Farmer/blob/41a665684d8f7efc5ddeb96322f1190c9cd021b9/main.py#L234) IIRC.

**Pull request closed without merging**
